config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'
  get '/admin' => 'landing#admin'

  get '/receipts/filtered'
  resources :receipts
  resources :auditoria
  resources :movies
  resources :showtimes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/auditoria_controller.rb
class AuditoriaController < ApplicationController
  before_action :set_auditorium, only: %i[ show edit update destroy ]

  # GET /auditoria or /auditoria.json
  def index
    @auditoria = Auditorium.all
  end

  # GET /auditoria/1 or /auditoria/1.json
  def show
  end

  # GET /auditoria/new
  def new
    @auditorium = Auditorium.new
  end

  # GET /auditoria/1/edit
  def edit
  end

  # POST /auditoria or /auditoria.json
  def create
    @auditorium = Auditorium.new(auditorium_params)

    respond_to do |format|
      if @auditorium.save
        format.html { redirect_to @auditorium, notice: "Auditorium was successfully created." }
        format.json { render :show, status: :created, location: @auditorium }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @auditorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auditoria/1 or /auditoria/1.json
  def update
    respond_to do |format|
      if @auditorium.update(auditorium_params)
        format.html { redirect_to @auditorium, notice: "Auditorium was successfully updated." }
        format.json { render :show, status: :ok, location: @auditorium }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @auditorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auditoria/1 or /auditoria/1.json
  def destroy
    @auditorium.destroy
    respond_to do |format|
      format.html { redirect_to auditoria_url, notice: "Auditorium was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auditorium
      @auditorium = Auditorium.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def auditorium_params
      params.require(:auditorium).permit(:name, :seat_capacity)
    end
end

app/helpers/auditoria_helper.rb
module AuditoriaHelper
end

app/views/auditoria/_form.html.slim
== render 'landing/banner', checked: true
= form_for @auditorium do |f|
  - if @auditorium.errors.any?
    #error_explanation
      h2 = "#{pluralize(@auditorium.errors.count, "error")} prohibited this auditorium from being saved:"
      ul
        - @auditorium.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :seat_capacity
    = f.text_field :seat_capacity
  .actions = f.submit

app/views/auditoria/edit.html.slim
== render 'form'

=> link_to 'Show', @auditorium
'|
=< link_to 'Back', auditoria_path

app/views/auditoria/index.html.slim
== render 'landing/banner', checked: true
h1 Auditoria

table
  thead
    tr
      th Name
      th Seat capacity
      th
      th
      th

  tbody
    - @auditoria.each do |auditorium|
      tr
        td = auditorium.name
        td = auditorium.seat_capacity
        td = link_to 'Edit', edit_auditorium_path(auditorium)
        td = link_to 'Destroy', auditorium, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Auditorium', new_auditorium_path

app/views/auditoria/new.html.slim
== render 'form'

.link
  = link_to 'Back', auditoria_path

app/views/auditoria/show.html.slim
p#notice = notice

p
  strong Seat capacity:
  = @auditorium.seat_capacity

=> link_to 'Edit', edit_auditorium_path(@auditorium)
'|
=< link_to 'Back', auditoria_path