config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'
  get '/admin' => 'landing#admin'

  get '/receipts/filtered'
  resources :receipts
  resources :auditoria
  resources :movies
  resources :showtimes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/showtime.rb
class Showtime < ApplicationRecord
  belongs_to :movie
  belongs_to :auditorium

  has_many :receipts, dependent: :destroy

  def seat_purchased!
    unless self.seats_full?
      self.seats_purchased += 1
      self.save!
    end
  end

  def seats_full?
    if self.seats_purchased == self.auditorium.seat_capacity
      true
    else
      false
    end
  end
end

app/controllers/showtimes_controller.rb
class ShowtimesController < ApplicationController
  before_action :set_showtime, only: %i[ show edit update destroy ]

  # GET /showtimes or /showtimes.json
  def index
    @showtimes = Showtime.all.sort_by(&:start_time).group_by{ |showtime| showtime.start_time.to_date}.transform_values do |shows|
      shows.group_by{ |showtime| showtime.movie.title }
    end
  end

  # GET /showtimes/1 or /showtimes/1.json
  def show
  end

  # GET /showtimes/new
  def new
    get_options
    @showtime = Showtime.new
  end

  def get_options
    @movie_options = Movie.all.map{ |movie| [movie.title, movie.id] }
    @auditorium_options = Auditorium.all.map{ |auditorium| [auditorium.name, auditorium.id] }
  end

  # GET /showtimes/1/edit
  def edit
    get_options
  end

  # POST /showtimes or /showtimes.json
  def create
    @get_options
    @showtime = Showtime.new(showtime_params)

    respond_to do |format|
      if @showtime.save
        format.html { redirect_to @showtime, notice: "Showtime was successfully created." }
        format.json { render :show, status: :created, location: @showtime }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @showtime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /showtimes/1 or /showtimes/1.json
  def update
    respond_to do |format|
      if @showtime.update(showtime_params)
        format.html { redirect_to @showtime, notice: "Showtime was successfully updated." }
        format.json { render :show, status: :ok, location: @showtime }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @showtime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /showtimes/1 or /showtimes/1.json
  def destroy
    @showtime.destroy
    respond_to do |format|
      format.html { redirect_to showtimes_url, notice: "Showtime was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_showtime
      @showtime = Showtime.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def showtime_params
      params.require(:showtime).permit(:start_time, :end_time, :seats_purchased, :movie_id, :auditorium_id)
    end
end

app/helpers/showtimes_helper.rb
module ShowtimesHelper
end

app/views/showtimes/_form.html.slim
== render 'landing/banner', checked: true
= form_for @showtime do |f|
  - if @showtime.errors.any?
    #error_explanation
      h2 = "#{pluralize(@showtime.errors.count, "error")} prohibited this showtime from being saved:"
      ul
        - @showtime.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :start_time
    = f.datetime_select :start_time
  .field
    = f.label :end_time
    = f.datetime_select :end_time
  .field
    = f.label :seats_purchased
    = f.text_field :seats_purchased, disabled: true
  .field
    = f.label :movie_id
    = f.select :movie_id, @movie_options
  .field
    = f.label :auditorium_id
    = f.select :auditorium_id, @auditorium_options

  .actions = f.submit
  .destroy
    | #{link_to 'Destroy', @showtime, data: { confirm: 'Are you sure?' }, method: :delete}

app/views/showtimes/edit.html.slim
== render 'form'

=> link_to 'Show', @showtime
'|
=< link_to 'Back', showtimes_path

app/views/showtimes/index.html.slim
== render 'landing/banner', checked: true
.page-content
  h2 Edit Showtimes
  = link_to 'New Showtime', new_showtime_path
  - @showtimes.each do |day, movies|
    .day-panel
      .day-title == day.strftime('%B %e, %Y')
      .day-content
        - movies.each do |movie, shows|
          .card
            .card-title == movie
            .card-content
              - shows.each do |show|
                - if show.seats_full?
                  a.capsule.full href="#{edit_showtime_path(show)}"
                    | #{show.start_time.strftime('%l:%M %p')} - #{show.end_time.strftime('%l:%M %p')}
                - else
                  a.capsule href="#{edit_showtime_path(show)}"
                    | #{show.start_time.strftime('%l:%M %p')} - #{show.end_time.strftime('%l:%M %p')}

app/views/showtimes/new.html.slim
== render 'form'

.link
  = link_to 'Back', showtimes_path

app/views/showtimes/show.html.slim
p#notice = notice

p
  strong Start time:
  = @showtime.start_time
p
  strong End time:
  = @showtime.end_time
p
  strong Seats purchased:
  = @showtime.seats_purchased

p
  strong Movie:
  = Movie.find(@showtime.movie_id)&.title

p
  strong Auditorium
  = Auditorium.find(@showtime.auditorium_id)&.name

=> link_to 'Edit', edit_showtime_path(@showtime)
'|
=< link_to 'Back', showtimes_path