config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'
  get '/admin' => 'landing#admin'

  get '/receipts/filtered'
  resources :receipts
  resources :auditoria
  resources :movies
  resources :showtimes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :showtime

  validates :customer_name, presence: true
  validates :customer_email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :credit_card_number, presence: true
  validates :credit_card_expiration, presence: true

  validate :card_number

  def card_number
    unless CreditCardValidator::Validator.valid?(self.credit_card_number)
      errors.add(:credit_card_number, "is not valid.")
    end
  end

end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  before_action :set_receipt, only: %i[ show edit update destroy ]

  # GET /receipts or /receipts.json
  def index
    @receipts = {'receipts' => Receipt.all}
  end

  def filtered
    @receipts = Receipt.all.group_by{ |receipt| receipt.showtime&.movie }
  end

  # GET /receipts/1 or /receipts/1.json
  def show
  end

  # GET /receipts/new
  def new
    @receipt = Receipt.new
    if params[:showtime_id].present?
      @receipt.showtime = Showtime.find params[:showtime_id]
    else
      raise 'Cannot create Receipt without Showtime ID'
    end
  end

  # GET /receipts/1/edit
  def edit
  end

  # POST /receipts or /receipts.json
  def create
    @receipt = Receipt.new(receipt_params)

    respond_to do |format|
      if @receipt.save
        format.html { redirect_to '/', notice: "Purchase successful, enjoy #{@receipt.showtime.movie.title}!" }
        format.json { render :show, status: :created, location: @receipt }

        @receipt.showtime.seat_purchased!

        ReceiptMailer.with(receipt: @receipt).receipt_email.deliver_now

      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receipts/1 or /receipts/1.json
  def update
    respond_to do |format|
      if @receipt.update(receipt_params)
        format.html { redirect_to @receipt, notice: "Receipt was successfully updated." }
        format.json { render :show, status: :ok, location: @receipt }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1 or /receipts/1.json
  def destroy
    @receipt.destroy
    respond_to do |format|
      format.html { redirect_to receipts_url, notice: "Receipt was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receipt
      @receipt = Receipt.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def receipt_params
      params.require(:receipt).permit(:purchased_at, :credit_card_number, :credit_card_expiration, :customer_name, :customer_email, :showtime_id)
    end
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/receipts/_form.html.slim
== render 'landing/banner', checked: false
= form_for @receipt do |f|
  - if @receipt.errors.any?
    #error_explanation
      h2 = "#{pluralize(@receipt.errors.count, "error")} prohibited this receipt from being saved:"
      ul
        - @receipt.errors.full_messages.each do |message|
          li = message

  = f.hidden_field :showtime_id
  = f.hidden_field :purchased_at, value: Date.today

  - @showtime = @receipt.showtime
  h3
    | Purchase Ticket for #{@showtime.movie.title} at #{@showtime.start_time.strftime('%l:%M %p')} on #{@showtime.start_time.strftime('%B %e, %Y')}

  .field
    = f.label :customer_name
    = f.text_field :customer_name
  .field
    = f.label :customer_email
    = f.text_field :customer_email
  .field
    = f.label :credit_card_number
    = f.text_field :credit_card_number
  .field
    = f.label :credit_card_expiration
    = f.date_field :credit_card_expiration
  .actions = f.submit "Purchase Ticket"

app/views/receipts/edit.html.slim
== render 'form'

=> link_to 'Show', @receipt
'|
=< link_to 'Back', receipts_path

app/views/receipts/filtered.html.slim
== render 'landing/banner', checked: true
.page-content
  h4 Filter by Movie
  .filter-toggle
    input.checkbox#filterToggle type='checkbox' checked=true data-checked="true"
    label.switch for='filterToggle'
    - @receipts.each do |movie, receipts|
      .day-panel
        .day-title
          | Movie: #{movie.title}
        .day-content
          - receipts.each do |receipt|
            .card
              .card-content
                a href="#{}"
                h4
                  | Showtime: #{receipt.showtime.start_time.strftime('%l:%M %p')}
                h4
                  | Price: $#{sprintf('%.2f', receipt.showtime.price)}
                h4
                  | Credit Card Ending in: ****#{receipt.credit_card_number[-4..-1]}



coffee:
  $('#filterToggle').click (evt) =>
      Turbolinks.visit('/receipts')

app/views/receipts/index.html.slim
== render 'landing/banner', checked: true
.page-content
  h4 Filter by Movie
  .filter-toggle
    input.checkbox#filterToggle type='checkbox' checked=false data-checked="false"
    label.switch for='filterToggle'
    - @receipts.each do |movie, receipts|
      .day-panel
        .day-title
          | All Receipts
        .day-content
          - receipts.each do |receipt|
            .card
              .card-content
                a href="#{}"
                h4
                  | Movie: #{receipt.showtime&.movie.title}
                h4
                  | Showtime: #{receipt.showtime&.start_time.strftime('%l:%M %p')}
                h4
                  | Price: $#{sprintf('%.2f', receipt&.showtime.price)}
                h4
                  | Credit Card Ending in: ****#{receipt&.credit_card_number[-4..-1]}

coffee:
  $('#filterToggle').click (evt) =>
    Turbolinks.visit('/receipts/filtered')

app/views/receipts/new.html.slim
== render 'form'

.link
  = link_to 'Back', '/'

app/views/receipts/show.html.slim
p#notice = notice

p
  strong Purchased at:
  = @receipt.purchased_at

=> link_to 'Edit', edit_receipt_path(@receipt)
'|
=< link_to 'Back', receipts_path